### ISSUE TITLE
Create Benchmarks

### ISSUE THREAD

**Issue by DanielSokil** [jgnewman/lightningDOM#1]
How does lightning DOM compare against [morphdom](https://github.com/patrick-steele-idem/morphdom) and [snabbdom](https://github.com/snabbdom/snabbdom)?

**Comment by jgnewman** [comment]
@DanielSokil I can't speak to snabbdom, but I did attempt to write some informal benchmarks that included morphdom. If you look in the repo now you'll still see the benchmarks but you won't see morphdom included. The reason is because, since morphdom doesn't use a virtual DOM and instead crawls and manipulates only the real DOM, it couldn't perform a single iteration of the benchmark test without crashing the browser (which is why virtual DOMs were invented :grinning: ). I'm open to the idea that I just didn't do it right. So if you'd like to pull and see if you can get morphdom and snabbdom running the benchmarks successfully, feel free. The benchmarks I've included are pretty informal, but they're still insightful, so I'm feeling good about it at this point.
